name: DeepSeek Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deepseek-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '\.java$' | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Analyze code with DeepSeek API
        id: analyze-code
        run: |
          for file in $CHANGED_FILES; do
            echo "Analyzing $file"
            CODE=$(cat $file | jq -sR .)
            RESPONSE=$(curl -s -X POST "${{ secrets.OLLAMA_API_URL }}/analyze" \
              -H "Content-Type: application/json" \
              -d "{\"language\": \"java\", \"code\": $CODE}")
            echo "REVIEW_$file<<EOF" >> $GITHUB_ENV
            echo "$RESPONSE" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          done

      - name: Post comments on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const files = process.env.CHANGED_FILES.split(' ');
            for (const file of files) {
              const comment = process.env[`REVIEW_${file}`];
              if (!comment) continue;
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: `### DeepSeek Code Review for ${file}\n\n${comment}`
              });
            }
